# Generated by Django 4.0 on 2022-10-04 06:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('year', models.DateField(verbose_name='Год выпуска')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('num_songs', models.IntegerField(verbose_name='Кол-во треков')),
                ('description', models.TextField(verbose_name='Описание')),
                ('label', models.CharField(max_length=100, verbose_name='Лейбл')),
                ('poster', models.ImageField(blank=True, upload_to='%Y/%m/%d/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Никнейм')),
                ('about', models.TextField(verbose_name='Об артисте')),
                ('home_town', models.CharField(max_length=50, verbose_name='Родной город')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to='%Y/%m/%d/', verbose_name='Трек')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=100, unique=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_album', to='music_library.album', verbose_name='Альбом')),
                ('artist', models.ManyToManyField(related_name='song_artist', to='music_library.Artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums_all', to='music_library.artist', verbose_name='Исполнитель'),
        ),
    ]
