# Generated by Django 4.1.1 on 2022-10-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0002_remove_song_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='poster',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/', verbose_name='Обложка'),
        ),
    ]
