# Generated by Django 4.1.1 on 2023-08-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0007_remove_playlist_song_playlist_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(related_name='artist_albums', to='music_library.album', verbose_name='Альбомы'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(blank=True, related_name='song_play', to='music_library.song', verbose_name='Треки'),
        ),
    ]
